# sonar-project.properties
sonar.projectKey=Zeth-21_bruno-ferrini-checkout-tdd
sonar.organization=zeth-21
sonar.projectName=SGI InkaRetail - Bruno Ferrini Checkout TDD

# Carpetas a analizar y exclusiones
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

# Ruta del reporte que generó tu pipeline
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8