# sonar-project.properties
sonar.projectKey=manu-cracks_PruebasUnitarias_BrunoFerrini2
sonar.organization=manu-cracks
sonar.projectName=PruebasUnitarias_BrunoFerrini

# Carpetas a analizar y exclusiones
sonar.sources=src
sonar.tests=tests
sonar.exclusions=node_modules/**,coverage/**

# Ruta del reporte que generó tu pipeline
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8