# .github/workflows/ci-jest.yml
name: CI - Tests Unitarios Jest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-unitarios:
    name: Ejecutar suite Jest
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v5

      - name: Instalar Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: 'npm'

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar tests con Cobertura (Quality Gate)
        run: npm run test:coverage

      # ==========================================
      # NUEVO PASO: SUBIR EL REPORTE DE COBERTURA
      # ==========================================
      - name: Guardar reporte como artefacto
        uses: actions/upload-artifact@v4
        if: always() # Obliga a subirlo incluso si algún test llega a fallar
        with:
          name: reporte-cobertura-bruno-ferrini # El nombre que tendrá el archivo zip
          path: coverage/lcov-report/            # La ruta de la carpeta que va a empaquetar
          retention-days: 7                     # El reporte se guardará en GitHub por 7 días