# .github/workflows/ci-jest.yml
# Pipeline: ejecuta los tests de Jest en cada Push o Pull Request a main
name: CI - Tests Unitarios Jest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-unitarios:
    name: Ejecutar suite Jest
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el código del repositorio
      - name: Descargar código
        uses: actions/checkout@v4

      # Paso 2: Instalar Node.js 20 (versión oficial del curso)
      - name: Instalar Node.js 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      # Paso 3: Instalar las dependencias del proyecto (incluye Jest)
      - name: Instalar dependencias
        run: npm install

      # Paso 4: Ejecutar todos los tests unitarios
      - name: Ejecutar tests con cobertura (Quality Gate)
        run: npm run test:coverage



      # ==========================================
      #INTEGRACIÓN CON SONARCLOUD
      # ==========================================
      - name: Análisis SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    



      # ==========================================
      # REPORTE DE COBERTURA
      # ==========================================
      - name: Guardar reporte como artefacto
        uses: actions/upload-artifact@v4
        if: always() 
        with:
          name: reporte-cobertura-bruno-ferrini 
          path: coverage/lcov-report/            
          retention-days: 12